#include "pch.h" // IWYU pragma: keep
#include "arena.h"
#include "glyph_cache.h"
#include "lib.h"

#include <stdint.h>
#include <stdlib.h>
#include <winuser.h>

//
// font
//

static void font_init(Font* font, IDWriteFactory3* dwrite_factory, const wchar_t* font_name, const f32 font_size)
{
    IDWriteFont* dw_font = NULL;
    {
        IDWriteFontFamily* font_family = NULL;
        {
            IDWriteFontCollection* font_collection = NULL;
            IDWriteFactory3_GetSystemFontCollection(dwrite_factory, &font_collection, FALSE);

            u32 family_index = 0;
            b32 family_exists = FALSE;
            IDWriteFontCollection_FindFamilyName(font_collection, font_name, &family_index, &family_exists);
            Assert(family_exists);

            IDWriteFontCollection_GetFontFamily(font_collection, family_index, &font_family);
            IDWriteFontCollection_Release(font_collection);
        }
        IDWriteFontFamily_GetFirstMatchingFont(font_family, DWRITE_FONT_WEIGHT_NORMAL, DWRITE_FONT_STRETCH_NORMAL,
                                               DWRITE_FONT_STYLE_NORMAL, &dw_font);
        IDWriteFontFamily_Release(font_family);
    }
    IDWriteFont_CreateFontFace(dw_font, &font->face);
    IDWriteFont_Release(dw_font);

    IDWriteFontFace_QueryInterface(font->face, &IID_IDWriteFontFace3, (void**)&font->face3);

    font->size = font_size;
}

// TODO: Not used
static void font_deinit(Font* font)
{
    if (font->face3)
    {
        IDWriteFontFace3_Release(font->face3);
        font->face3 = NULL;
    }
    if (font->face)
    {
        IDWriteFontFace_Release(font->face);
        font->face = NULL;
    }
    font->size = 0.0f;
}

//
// glyph
//

// TODO: For small font size, ClearType provides a better appearance compared to GrayScale. In the future,
// we might want to implement ClearType support. The [dwrite-hlsl](https://github.com/lhecker/dwrite-hlsl)
// library could be useful for blending when this change is made.
//
// NOTE: the bbox (bound) of ' ' glyph is (0, 0, 0, 0).
// NOTE: `IDWriteGlyphRunAnalysis_CreateAlphaTexture` does support rasterize multi glyphs, but I have no idea how to get
// each glyph metrics of the bitmap generated by it. If just rasterize one glyph one time, then xoff, yoff just equal
// bound_left/top.
static u8* glyph_get(Arena* arena, IDWriteFactory3* dwrite_factory, Font* font, const u32 codepoint, Glyph* glyph, const u32 dpi)
{
    glyph->font = font;

    // Get pixel size & scale, see: https://learn.microsoft.com/en-us/windows/win32/learnwin32/dpi-and-device-independent-pixels
    DWRITE_FONT_METRICS font_metrics = { 0 };
    IDWriteFontFace_GetMetrics(font->face, &font_metrics);
    f32 dpi_scale = (f32)dpi / USER_DEFAULT_SCREEN_DPI;
    f32 physical_pixel_size = font->size * dpi_scale;

    // Get glyph indices
    glyph->codepoint = codepoint;
    u32 codepoints[1] = { glyph->codepoint };
    u16 glyph_indices[1] = { 0 };
    IDWriteFontFace_GetGlyphIndices(font->face, codepoints, 1, glyph_indices);

    // Get glyph advances
    f32 metrics_scale = physical_pixel_size / (f32)font_metrics.capHeight;
    DWRITE_GLYPH_METRICS design_metrics[1] = { 0 };
    IDWriteFontFace3_GetDesignGlyphMetrics(font->face3, glyph_indices, 1, design_metrics, FALSE);
    f32 glyph_advances[1] = { design_metrics[0].advanceWidth * metrics_scale };
    glyph->xadvance = (u32)glyph_advances[0];

    // Get glyph offsets
    DWRITE_GLYPH_OFFSET glyph_offsets[1] = { 0 };

    // Glyph run analysis
    DWRITE_GLYPH_RUN run = {
        .fontFace = font->face,
        .fontEmSize = (f32)font_metrics.designUnitsPerEm * metrics_scale,
        .glyphCount = 1,
        .glyphIndices = glyph_indices,
        .glyphAdvances = glyph_advances,
        .glyphOffsets = glyph_offsets,
    };

    DWRITE_GRID_FIT_MODE grid_fit_mode = DWRITE_GRID_FIT_MODE_DEFAULT;
    DWRITE_RENDERING_MODE1 rendering_mode = DWRITE_RENDERING_MODE1_NATURAL_SYMMETRIC;

    IDWriteGlyphRunAnalysis* analysis = NULL;
    IDWriteFactory3_CreateGlyphRunAnalysis2(
        /* this             */ dwrite_factory,
        /* glyphRun         */ &run,
        /* transform        */ NULL,
        /* renderingMode    */ rendering_mode,
        /* measuringMode    */ DWRITE_MEASURING_MODE_NATURAL,
        /* gridFitMode      */ grid_fit_mode,
        /* antialiasMode    */ DWRITE_TEXT_ANTIALIAS_MODE_GRAYSCALE,
        /* baselineOriginX  */ 0.0f,
        /* baselineOriginY  */ 0.0f,
        /* glyphRunAnalysis */ &analysis);

    // Create glyph bitmap
    u8* glyph_bitmap;
    {
        // DWRITE_TEXTURE_ALIASED_1x1 is a misnomer, It actually outputs grayscale if we set up the analysis with AA enabled
        const DWRITE_TEXTURE_TYPE type = DWRITE_TEXTURE_ALIASED_1x1;

        RECT bounds = { 0 };
        IDWriteGlyphRunAnalysis_GetAlphaTextureBounds(analysis, type, &bounds);

        glyph->xoff = bounds.left;
        glyph->yoff = bounds.top;
        glyph->w = bounds.right - bounds.left;
        glyph->h = bounds.bottom - bounds.top;

        u32 bitmap_size = glyph->w * glyph->h;
        glyph_bitmap = arena_push(arena, sizeof(u8), _Alignof(u8), bitmap_size);
        IDWriteGlyphRunAnalysis_CreateAlphaTexture(analysis, type, &bounds, glyph_bitmap, bitmap_size);
        IDWriteGlyphRunAnalysis_Release(analysis);
    }
    return glyph_bitmap;
}

//
// glyph cache
//
// NOTE: Currently, it lacks advanced features such as LRU (Least Recently Used) management or
// other optimization techniques, serving merely as a straightforward storage mechanism for glyphs
// and their associated atlas data.
//

static void glyph_cache_init(GlyphCache* glyph_cache, const isize glyphs_length)
{
    GlyphAtlas* atlas = &glyph_cache->atlas;
    atlas->bitmap = arena_push(&glyph_cache->arena, sizeof(u8), _Alignof(u8), atlas->w * atlas->h);

    glyph_cache->glyphs = arena_push(&glyph_cache->arena, sizeof(Glyph), _Alignof(Glyph), glyphs_length);
}

void glyph_cache_deinit(GlyphCache* glyph_cache)
{
    memset(&glyph_cache->font, 0, sizeof(glyph_cache->font));
    glyph_cache->glyphs = NULL;

    GlyphAtlas* atlas = &glyph_cache->atlas;
    atlas->maxy = 0;
    atlas->next_x = 0;
    atlas->next_y = 0;

    arena_pop_to(&glyph_cache->arena, 0);
}

static void glyph_cache_pack_codepoints(GlyphCache* glyph_cache, IDWriteFactory3* dwrite_factory, Font* font, const u32* codepoints, const isize codepoints_length, const u32 dpi)
{
    // Insert glyph to atlas and get relative position information for glyphs & glyph_atlas
    GlyphAtlas* atlas = &glyph_cache->atlas;
    isize arena_pos_backup = glyph_cache->arena.pos;
    for (isize i = 0; i < codepoints_length; i++)
    {
        Glyph* glyph = &glyph_cache->glyphs[i];
        u8* glyph_bitmap = glyph_get(&glyph_cache->arena, dwrite_factory, font, codepoints[i], glyph, dpi);

        // Update the position information of glyph and atlas
        atlas->maxy = max(atlas->maxy, atlas->next_y + glyph->h);
        Assert(atlas->maxy <= atlas->h);
        if (atlas->next_x + glyph->w > atlas->w)
        {
            Assert(atlas->maxy + glyph->h <= atlas->h);
            atlas->next_y = atlas->maxy;
            atlas->next_x = 0;
        }
        glyph->atlas_x = atlas->next_x;
        glyph->atlas_y = atlas->next_y;

        // Insert glyph bitmap into the glyph atlas bitmap
        for (u32 y = 0; y < glyph->h; y++)
        {
            for (u32 x = 0; x < glyph->w; x++)
            {
                u8 grayscale = glyph_bitmap[glyph->w * y + x];
                atlas->bitmap[(atlas->next_y + y) * atlas->w + (atlas->next_x + x)] = grayscale;
            }
        }
        atlas->next_x += glyph->w;

    }
    arena_pop_to(&glyph_cache->arena, arena_pos_backup);
}

//
// temp
//

// TODO: Currently only include ASCII characters, custom icons from a specified font, and a small
// white region to render solid-colored rectangles.
// TODO: Need to handle multiple fonts
void glyph_cache_init_and_fill(GlyphCache* glyph_cache, const wchar_t* font_family, const f32 font_size, const u32 dpi)
{
    glyph_cache_init(glyph_cache, GLYPHS_LENGTH);

    // Create dwrite factory & font
    IDWriteFactory3* dwrite_factory = NULL;
    DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, &IID_IDWriteFactory, (void**)&dwrite_factory);

    font_init(&glyph_cache->font, dwrite_factory, font_family, font_size);

    // Pack ascii & icons glyphs
    u32 codepoints[GLYPHS_LENGTH - 1];
    {
        u32 i;
        for (i = 0; i < GLYPHS_LENGTH - 2; i++)
            codepoints[i] = i + ASCII_START;
        codepoints[i] = 57569;
    }
    glyph_cache_pack_codepoints(glyph_cache, dwrite_factory, &glyph_cache->font, codepoints, GLYPHS_LENGTH - 1, dpi);

    // Insert a 3x3 white region to bottom-right corner of glyph atlas
    Glyph* white_glyph = &glyph_cache->glyphs[GLYPHS_LENGTH - 1];
    white_glyph->atlas_x = GLYPH_ATLAS_WIDTH - 3;
    white_glyph->atlas_y = GLYPH_ATLAS_HEIGHT - 3;
    white_glyph->w = 3;
    white_glyph->h = 3;
    for (isize y = 0; y < 3; y++)
        for (isize x = 0; x < 3; x++)
            glyph_cache->atlas.bitmap[(white_glyph->atlas_y + y) * GLYPH_ATLAS_WIDTH + (white_glyph->atlas_x + x)] = 255;

    // Clean
    IDWriteFactory3_Release(dwrite_factory);
}
