#include "glyph_cache.h"
#include "lib.h"
#include "thirdparty/cdwrite.h"

#include <stdint.h>
#include <stdlib.h>

//
// font
//

Font* font_create(IDWriteFactory3* dwrite_factory, const wchar_t* font_name, const float font_size, const float dpi)
{
    Font* font = malloc(sizeof(Font));

    IDWriteFont* dw_font = NULL;
    {
        IDWriteFontFamily* font_family = NULL;
        {
            IDWriteFontCollection* font_collection = NULL;
            IDWriteFactory3_GetSystemFontCollection(dwrite_factory, &font_collection, FALSE);

            UINT32 family_index = 0;
            BOOL family_exists = FALSE;
            IDWriteFontCollection_FindFamilyName(font_collection, font_name, &family_index, &family_exists);
            Assert(family_exists);

            IDWriteFontCollection_GetFontFamily(font_collection, family_index, &font_family);
            IDWriteFontCollection_Release(font_collection);
        }
        IDWriteFontFamily_GetFirstMatchingFont(font_family, DWRITE_FONT_WEIGHT_NORMAL, DWRITE_FONT_STRETCH_NORMAL,
                                               DWRITE_FONT_STYLE_NORMAL, &dw_font);
        IDWriteFontFamily_Release(font_family);
    }
    IDWriteFont_CreateFontFace(dw_font, &font->face);
    IDWriteFont_Release(dw_font);

    IDWriteFontFace_QueryInterface(font->face, &IID_IDWriteFontFace3, (void**)&font->face3);

    font->size = font_size;
    font->dpi = dpi;
    return font;
}

void font_destroy(Font* font)
{
    if (font->face3)
    {
        IDWriteFontFace3_Release(font->face3);
        font->face3 = NULL;
    }
    if (font->face)
    {
        IDWriteFontFace_Release(font->face);
        font->face = NULL;
    }
    font->size = 0.0f;
    font->dpi = 0.0f;
}

//
// glyph
//

// TODO: For small font size, ClearType provides a better appearance compared to GrayScale. In the future,
// we might want to implement ClearType support. The [dwrite-hlsl](https://github.com/lhecker/dwrite-hlsl)
// library could be useful for blending when this change is made.
//
// NOTE: the bbox (bound) of ' ' glyph is (0, 0, 0, 0).
// NOTE: `IDWriteGlyphRunAnalysis_CreateAlphaTexture` does support rasterize multi glyphs, but I have no idea how to get
// each glyph metrics of the bitmap generated by it. If just rasterize one glyph one time, then xoff, yoff just equal
// bound_left/top.
static uint8_t* glyph_get(IDWriteFactory3* dwrite_factory, Font* font, const uint16_t codepoint, Glyph* glyph)
{
    glyph->font = font;

    // https://learn.microsoft.com/en-us/windows/win32/learnwin32/dpi-and-device-independent-pixels
    float font_em_size = font->size / (font->dpi / 96.0f);

    // Get glyph indices
    glyph->codepoint = codepoint;
    uint32_t codepoints[1] = { glyph->codepoint };
    UINT16 glyph_indices[1] = { 0 };
    IDWriteFontFace_GetGlyphIndices(font->face, codepoints, 1, glyph_indices);

    // Get font metrics & scale & design metrics
    DWRITE_FONT_METRICS font_metrics = { 0 };
    IDWriteFontFace_GetMetrics(font->face, &font_metrics);
    float scale = font_em_size / (float)font_metrics.designUnitsPerEm;
    {
        glyph->font->ascent = (uint16_t)((float)font_metrics.ascent * scale);
        glyph->font->descent = (uint16_t)((float)font_metrics.descent * scale);
        glyph->font->line_gap = (int16_t)((float)font_metrics.lineGap * scale);
        glyph->font->english_capital_height = (uint16_t)((float)font_metrics.capHeight * scale);
    }
    DWRITE_GLYPH_METRICS design_metrics[1] = { 0 };
    IDWriteFontFace3_GetDesignGlyphMetrics(font->face3, glyph_indices, 1, design_metrics, FALSE);

    // Get glyph advances & glyph offsets
    float glyph_advances[1] = { design_metrics[0].advanceWidth * scale };
    DWRITE_GLYPH_OFFSET glyph_offsets[1] = { 0 };
    glyph->xadvance = (uint16_t)glyph_advances[0];

    // Glyph run analysis
    DWRITE_GLYPH_RUN run = {
        .fontFace = font->face,
        .fontEmSize = font_em_size, // The logical size of the font in DIPs (equals 1/96 inch), not points.
        .glyphCount = 1,
        .glyphIndices = glyph_indices,
        .glyphAdvances = glyph_advances,
        .glyphOffsets = glyph_offsets,
    };

    DWRITE_GRID_FIT_MODE grid_fit_mode = DWRITE_GRID_FIT_MODE_DEFAULT;
    DWRITE_RENDERING_MODE1 rendering_mode = DWRITE_RENDERING_MODE1_NATURAL_SYMMETRIC;

    IDWriteGlyphRunAnalysis* analysis = NULL;
    IDWriteFactory3_CreateGlyphRunAnalysis2(
        /* this             */ dwrite_factory,
        /* glyphRun         */ &run,
        /* transform        */ NULL,
        /* renderingMode    */ rendering_mode,
        /* measuringMode    */ DWRITE_MEASURING_MODE_NATURAL,
        /* gridFitMode      */ grid_fit_mode,
        /* antialiasMode    */ DWRITE_TEXT_ANTIALIAS_MODE_GRAYSCALE,
        /* baselineOriginX  */ 0.0f,
        /* baselineOriginY  */ 0.0f,
        /* glyphRunAnalysis */ &analysis);

    // Create glyph bitmap
    uint8_t* glyph_bitmap;
    {
        // DWRITE_TEXTURE_ALIASED_1x1 is a misnomer, It actually outputs grayscale if we set up the analysis with AA enabled
        const DWRITE_TEXTURE_TYPE type = DWRITE_TEXTURE_ALIASED_1x1;

        RECT bounds = { 0 };
        IDWriteGlyphRunAnalysis_GetAlphaTextureBounds(analysis, type, &bounds);

        glyph->xoff = (int16_t)bounds.left;
        glyph->yoff = (int16_t)bounds.top;
        glyph->w = (uint16_t)(bounds.right - bounds.left);
        glyph->h = (uint16_t)(bounds.bottom - bounds.top);

        UINT32 bitmap_size = glyph->w * glyph->h;
        glyph_bitmap = malloc(bitmap_size * sizeof(uint8_t));
        IDWriteGlyphRunAnalysis_CreateAlphaTexture(analysis, type, &bounds, glyph_bitmap, bitmap_size);
        IDWriteGlyphRunAnalysis_Release(analysis);
    }
    return glyph_bitmap;
}

//
// glyph atlas
//

static GlyphAtlas* glyph_atlas_create()
{
    GlyphAtlas* glyph_atlas = malloc(sizeof(GlyphAtlas));
    glyph_atlas->w = GLYPH_ATLAS_WIDTH;
    glyph_atlas->h = GLYPH_ATLAS_HEIGHT;
    glyph_atlas->bitmap = malloc(glyph_atlas->w * glyph_atlas->h * sizeof(uint8_t));
    memset(glyph_atlas->bitmap, 0, glyph_atlas->w * glyph_atlas->h * sizeof(uint8_t));
    glyph_atlas->next_x = 0;
    glyph_atlas->next_y = 0;
    glyph_atlas->maxy = 0;
    return glyph_atlas;
}

static void glyph_atlas_destroy(GlyphAtlas* glyph_atlas)
{
    free(glyph_atlas->bitmap);
    free(glyph_atlas);
}

//
// glyph cache
//
// Note: Currently, it lacks advanced features such as LRU (Least Recently Used) management or
// other optimization techniques, serving merely as a straightforward storage mechanism for glyphs
// and their associated atlas data.
//

void glyph_cache_init(GlyphCache* glyph_cache, const uint16_t glyphs_length)
{
    glyph_cache->atlas = glyph_atlas_create();
    glyph_cache->glyphs = malloc(glyphs_length * sizeof(Glyph));
}

void glyph_cache_pack_codepoints(IDWriteFactory3* dwrite_factory, GlyphCache* glyph_cache, Font* font, const uint32_t* codepoints, const uint16_t codepoints_length)
{
    // Insert glyph to atlas and get relative position information for glyphs & glyph_atlas
    GlyphAtlas* atlas = glyph_cache->atlas;
    for (int i = 0; i < codepoints_length; i++)
    {
        Glyph* glyph = &glyph_cache->glyphs[i];
        uint8_t* glyph_bitmap = glyph_get(dwrite_factory, font, codepoints[i], glyph);

        // Update the position information of glyph and atlas
        atlas->maxy = max(atlas->maxy, atlas->next_y + glyph->h);
        Assert(atlas->maxy <= atlas->h);
        if (atlas->next_x + glyph->w > atlas->w)
        {
            Assert(atlas->maxy + glyph->h <= atlas->h);
            atlas->next_y = atlas->maxy;
            atlas->next_x = 0;
        }
        glyph->atlas_x = atlas->next_x;
        glyph->atlas_y = atlas->next_y;

        // Insert glyph bitmap into the glyph atlas bitmap
        for (uint16_t y = 0; y < glyph->h; y++)
        {
            for (uint16_t x = 0; x < glyph->w; x++)
            {
                uint8_t grayscale = glyph_bitmap[glyph->w * y + x];
                atlas->bitmap[(atlas->next_y + y) * atlas->w + (atlas->next_x + x)] = grayscale;
            }
        }
        atlas->next_x += glyph->w;

        // Clean
        free(glyph_bitmap);
    }
}

void glyph_cache_deinit(GlyphCache* glyph_cache)
{
    free(glyph_cache->glyphs);
    glyph_atlas_destroy(glyph_cache->atlas);
    free(glyph_cache);
}

//
// temp
//

// TODO: Currently only include ASCII characters, custom icons from a specified font, and a small
// white region to render solid-colored rectangles.
void glyph_cache_init_and_fill(const HWND window, GlyphCache* glyph_cache, const wchar_t* font_family)
{
    glyph_cache_init(glyph_cache, GLYPHS_LENGTH);

    // Create dwrite factory & font
    IDWriteFactory3* dwrite_factory = NULL;
    DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED, &IID_IDWriteFactory, (void**)&dwrite_factory);
    float dpi = (float)GetDpiForWindow(window);

    // TODO: Need to handle DPI things
    Font* font = font_create(dwrite_factory, font_family, FONT_SIZE, dpi);

    // Pack ascii & icons glyphs
    uint32_t codepoints[GLYPHS_LENGTH - 1];
    {
        uint32_t i;
        for (i = 0; i < GLYPHS_LENGTH - 2; i++)
        {
            codepoints[i] = i + ASCII_START;
        }
        codepoints[i] = 57569;
    }
    glyph_cache_pack_codepoints(dwrite_factory, glyph_cache, font, codepoints, GLYPHS_LENGTH - 1);

    // Insert a 3x3 white region to bottom-right corner of glyph atlas
    Glyph* white_glyph = &glyph_cache->glyphs[GLYPHS_LENGTH - 1];
    white_glyph->atlas_x = GLYPH_ATLAS_WIDTH - 3;
    white_glyph->atlas_y = GLYPH_ATLAS_HEIGHT - 3;
    white_glyph->w = 3;
    white_glyph->h = 3;
    for (int y = 0; y < 3; y++)
    {
        for (int x = 0; x < 3; x++)
        {
            glyph_cache->atlas->bitmap[(white_glyph->atlas_y + y) * GLYPH_ATLAS_WIDTH + (white_glyph->atlas_x + x)] = 255;
        }
    }

    // Clean
    font_destroy(font);
    IDWriteFactory3_Release(dwrite_factory);
}
