"""
extract_pos_tags.py — Scan data/dict.json for all POS prefixes used in the
translation field, assign each to a canonical enum slot, and emit a C header
fragment for copy-pasting into main.c.

Usage:  python scripts/extract_pos_tags.py
"""

import json
import re
from collections import Counter
from pathlib import Path

JSON_PATH = Path("data/dict.json")


def extract_tags() -> Counter:
    """Return {raw_tag: count} for every distinct POS-like prefix in translations."""
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    counts = Counter()
    for entry in data.values():
        tr = entry.get("translation", "")
        if not tr:
            continue
        for part in tr.split("；"):
            part = part.strip()
            if not part:
                continue
            # Standard POS abbreviation (1-6 alpha chars, optional dot)
            m = re.match(r"^([a-zA-Z]{1,6})(?:\.)?(?=\s|[^\x00-\x7F])", part)
            if m:
                tag = m.group(1)
                if tag.isalpha() and len(tag) <= 6:
                    counts[tag] += 1
                    continue
            # Bracketed domain tag [计] [医] etc.
            m2 = re.match(r"^\[([^\]]+)\]", part)
            if m2:
                counts[f"[{m2.group(1)}]"] += 1
                continue
    return counts


# ─── canonical human-readable names ───────────────────────────────────────

# Mapping from raw tag → (enum_name, display_name).
# Anything not listed here gets POS_UNKNOWN and is displayed as-is.
CANONICAL = {
    # parts of speech
    "n":        ("POS_NOUN",                "noun"),
    "v":        ("POS_VERB",                "verb"),
    "vt":       ("POS_VERB_TRANSITIVE",     "vt."),
    "vi":       ("POS_VERB_INTRANSITIVE",   "vi."),
    "a":        ("POS_ADJ",                 "adj."),
    "adv":      ("POS_ADV",                 "adv."),
    "prep":     ("POS_PREP",                "prep."),
    "pron":     ("POS_PRON",                "pron."),
    "conj":     ("POS_CONJ",                "conj."),
    "interj":   ("POS_INTERJ",              "interj."),
    "int":      ("POS_INTERJ",              "interj."),  # alias
    "num":      ("POS_NUM",                 "num."),
    "abbr":     ("POS_ABBR",                "abbr."),
    "art":      ("POS_ART",                 "art."),
    "aux":      ("POS_AUX",                 "aux."),
    "pl":       ("POS_PL",                  "pl."),
    "pref":     ("POS_PREF",                "pref."),
    "su":       ("POS_SUFFIX",              "suf."),
    "vbl":      ("POS_VBL",                 "vbl."),
    # domain tags — displayed with brackets in Chinese context
    "[医]":     ("POS_DOMAIN_MED",          "[医]"),
    "[计]":     ("POS_DOMAIN_COMP",         "[计]"),
    "[法]":     ("POS_DOMAIN_LAW",          "[法]"),
    "[化]":     ("POS_DOMAIN_CHEM",         "[化]"),
    "[经]":     ("POS_DOMAIN_ECON",         "[经]"),
    "[机]":     ("POS_DOMAIN_MECH",         "[机]"),
    "[电]":     ("POS_DOMAIN_ELEC",         "[电]"),
    "[建]":     ("POS_DOMAIN_ARCH",         "[建]"),
    "[人名]":   ("POS_DOMAIN_NAME",         "[人名]"),
    "[地名]":   ("POS_DOMAIN_GEO",          "[地名]"),
    "[俚]":     ("POS_DOMAIN_SLANG",        "[俚]"),
    "[美俚]":   ("POS_DOMAIN_SLANG_US",     "[美俚]"),
    "[古]":     ("POS_DOMAIN_ARCHAIC",      "[古]"),
    "[网络]":   ("POS_DOMAIN_NET",          "[网络]"),
    "[圣经]":   ("POS_DOMAIN_BIBLE",        "[圣经]"),
}


def main():
    counts = extract_tags()

    # Collect every unique enum name
    enum_names = []
    name_entries = []
    seen_enums = set()
    for tag, (enum, display) in sorted(CANONICAL.items()):
        if enum not in seen_enums:
            seen_enums.add(enum)
            enum_names.append(enum)
            name_entries.append((enum, display))

    # Tag-to-enum lookup table (binary search at runtime, or just a linear scan
    # since we only have ~30 entries).  Sorted by tag for readability.
    raw_to_enum = []
    for tag, (enum, _display) in sorted(CANONICAL.items()):
        raw_to_enum.append((tag, enum))

    # ── Print C header ──
    print("// ─── PosKind enum (auto-generated by scripts/extract_pos_tags.py) ───")
    print()
    print("typedef enum")
    print("{")
    for ename in enum_names:
        print(f"    {ename},")
    print("    POS_UNKNOWN = 0xFF,")
    print("} PosKind;")
    print()
    print("static const char* s_pos_names[] = {")
    for enum, display in name_entries:
        print(f'    [{enum}] = "{display}",')
    print("};")
    print()
    print("// {raw_tag, PosKind} pairs for runtime lookup")
    print("static const struct { const char* tag; PosKind kind; } s_pos_tag_table[] = {")
    for tag, enum in raw_to_enum:
        print(f'    {{ "{tag}", {enum} }},')
    print("};")
    print()

    # ── Unmapped tags report ──
    unmapped = [(t, c) for t, c in counts.most_common() if t not in CANONICAL]
    if unmapped:
        print("// ─── Unmapped tags (displayed as-is; consider adding to CANONICAL) ───")
        for tag, count in unmapped:
            if count <= 2:
                break
            print(f"//   {tag:15s}  ({count})")
    else:
        print("// All tags mapped.")


if __name__ == "__main__":
    main()
